sudo: false
language: python
python:
- '2.7'
- '3.3'
- '3.4'
- '3.5'
- pypy
before_install:
- git fetch --unshallow
install:
- pip install pip pybuilder coveralls --upgrade
- pyb install_dependencies
script:
- pyb -X run_unit_tests
after_success:
- coveralls --verbose
before_deploy:
- pyb -X package
deploy:
  provider: pypi
  user: steveparker-kcom
  password:
    secure: R4YXQoaV+qBS/2PKh2QXmdh8iB2FQ9sHqfUCLhCRrCGPNwNkYNzUloe0J3mut/Gq6MGORjxMPsJ4xHbmqoVqGzEam6F2xsCuJD8fizU5HRWjomnZ2cPVC12NQNpS20eICxTVMJMANtVc6DnHYCvIE+1JrJqCzO1JeawfbS9Fxc+kuP9XPN0PN+JLVwClyaAwOUBjd1sRe08ClmRuvoxDrbCfNRv/xubYkbysvHkYJ2rieN+FSyhpD/NtiUx4Dkc8R/CalqT/cgFqCaoLY05cyR8SAw53hC1UWM8kIHNzJrHD6kwzSYjKkHKzR1ulyRoEVOiiZeJQso9KhcLmWa3ugF+PYCa8GYN1bjpQOTxku2z20GpKzXtxemJnu61rySh/7WsXsw6dej0bocgMtwMv2ozeR6wCqKwqcwt3TNhYBFAr5VJ3m091k/ecWS2V9Gj/L+9zuFX5Hc/pcHiWdNftHTxF8+9cb7V6JBzbHhcITKr7efv0mEnzbiC1PvvV9yLXg1zNxiSHmfTNuYEqBRkITNAG9xpRugCzpuDpgYMY2FgnyGmKUFtlSnA+zdJraBzozCGKY8mDG/B8AwWTk5JESeCZPU19VmsVI07UY8/rYXgki8lfJMLJO1eh6yzbbfkBdQ2X8/K49fqyCUxGtO154VOv81cnK1jYRiyYu7qzezE=
  distributions: sdist
  skip_cleanup: true
  on:
    repo: Smart421/cfn-square
    branch: master
    python: '3.5'
